import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Web Animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <video autoPlay muted loop className={styles.video}>         
        <source src="/videos/truckdrive.mp4" type="video/mp4"/>
      </video>

      <div className={styles.overlay}></div>
      
      <main className={styles.main}>
        <Link href="/scene/one" passHref><button className={`${styles['begin-btn']} ${styles["hvr-bob"]}`}>START</button></Link>
      </main>
    </div>
  )
}
